#!/usr/bin/env bash
function Schlep-Setup() {

  Schlep-LoadConfiguration

  [[ -z "$SCHLEP_HOME"    ]] && export SCHLEP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd )"
  [[ -z "$SCHLEP_SERVICE" ]] && export SCHLEP_SERVICE="$SCHLEP_HOME/server/schlep.sh"
  [[ -z "$SCHLEP_HOST"    ]] && export SCHLEP_HOST="localhost"

  Schlep-Log "HOME=$SCHLEP_HOME,SERVICE=$SCHLEP_SERVICE,HOST=$SCHLEP_HOST."
}
function Schlep-LoadConfiguration() {
    SCHLEP_CONFIGURATION="${HOME}/schlep.properties"
    if [[ -s "${SCHLEP_CONFIGURATION}" ]]; then
      source $SCHLEP_CONFIGURATION
    fi
}

function Schlep-Banner() {
  echo "[$1]:------------------------------------------" >> "$SCHLEP_HOME/.schlep"
}
function Schlep-Log() {
  echo "[$(date +%F_%T)]--Client:[$*]" 2>&1 >> "$SCHLEP_HOME/.schlep"
  [[ $? -ne 0 ]] && echo "[$(date +%F_%T)]--Client:[$*]"
}
function Schlep-Dump() {
  Schlep-Log "DUMP"
  $@ 2>&1 >> "$SCHLEP_HOME/.schlep"
}
function Schlep-Debug() {
  echo "DEBUG:#####($1)"
  cat  $1
  echo "#####:DEBUG"
}
function Schlep-Request() {
  ssh ${SCHLEP_HOST} "$SCHLEP_SERVICE $@" > $tmpfile
}
function Schlep-Resolve() {
  [[ -n "${SCHLEP_DEBUG}" ]] && Schlep-Debug $1

  chmod +x $1
  $1; status=$?

  [[ $status -eq  0 ]] && true
  [[ $status -ne  0 ]] && false
}
Schlep-Setup;
Schlep-Banner "BEGIN::Main"
Schlep-Log "[$0] -- ENTRY [$@]"

status=1
tmpfile=$(mktemp /tmp/schlep.XXXXXX)
  # Send the request to the server
  # ssh ${SCHLEP_HOST} "${SCHLEP_HOME}/server/schlep.sh $@" > $tmpfile
  Schlep-Request $@ > $tmpfile

  # Perform the client side resolution
  Schlep-Resolve $tmpfile

  [[ -z "${SCHLEP_DEBUG}" ]] && rm -f $tmpfile

Schlep-Banner "END  ::Main"
Schlep-Log "[$0] -- EXIT  [$status]"
exit $status
